#!/usr/bin/env python3

#Criando um dicionário com minhas coisas favoritas
fav_dict = { 'Livro' : 'Harry Potter' , 'Canção' : 'The archer', 'Árvore' : 'Ipê' }

#Imprimindo meu dicionário favorito
print(f'Dicionário das minhas coisas favoritas: {fav_dict}')

