#!/usr/bin/env python3

#Criando um dicionário com minhas coisas favoritas
fav_dict = { 'Livro' : 'Harry Potter' , 'Canção' : 'The archer', 'Árvore' : 'Ipê' }

#Imprimindo meu dicionário favorito
print(f'Dicionário das minhas coisas favoritas: {fav_dict}')

#Imprimindo meu livro favorito
print(f'Meu livro favorito é: {fav_dict["Livro"]}')

#Imprimindo meu livro favorito com uma variável na chave
fav_thing = 'Livro'
print(f'Meu livro favorito é (com a chave fav_thing): {fav_dict[fav_thing]}')

